### ISSUE TITLE
 restore the original near and far values in CullVisitor

### ISSUE THREAD

**Issue by RealityTracer** [openscenegraph/OpenSceneGraph#514] opened 2018-04-01 11:39 UTC
If the scene is only a camera attached to FBO, and autoComputeNearAndFar is open for master camera 
during applying the camera in CullVisitor, the restoration stage may has a shortcoming. I wanna the computed near and far plane, but they are replaced with the previous ones of CullVisitor during the restoration stage . The previous near and far are not valid , thus when computing the near and far for the master camera, the 'clampProjectionMatrix' func return false, leading the projection of master camera unchanged. One way to avoid this shortcoming is needing to add the scene to the master camera, but this seems to be redundant.

**Comment by openscenegraph** [comment] 2018-04-01 12:28
Could you create an example to illustrate what you think the problem is so that we can reproduce the issue and investigate whether it's a bug or just an error in what you are implementing.

As a general note, if your scene just has a FBO camera as a child then perhaps should just assign the FBO and it's sub-graph directly to the master Camera.   Also for general discussions please use the osg-users mailing list/forum as this venue for support, Issue tracking is only seen by a small portion of the community and is meant just for bugs/build problems.

**Comment by RealityTracer** [comment] 2018-04-01 12:42
But, I really do not want to draw the  sub-graph  in the master camera one more time. Why need to draw one more time! For example, I just want to retrieve a 32bit floating-point depth buffer, and use the floating-point depth buffe to compare with the computed depth, the depth computation needs the automatically clamped projection in the cullVisitor. But the projection matrix of master camera will not be clamped when calling  '_cullVisitor->clampProjectionMatrix(getProjectionMatrix(),zNear,zFar);'--->line 763

**Comment by openscenegraph** [comment] 2018-04-01 13:51
It's not normal usage case you are discussing so there without more information like a compilable test case illustrating the issue there really isn't much we can do, it's just too many unknowns, only you know the code in front of you and the problem you are trying to solve and what you think is going wrong.  

It's also impossible to guess what you know about the OSG and what you level understanding is about the underlying concepts, it could well be enitrely the wrong approach you are taking. 

So please, create a simple example illustrating the problem, tell us what version of the OSG you are using, how we can recreate the issue ourselves and post a thread on osg-users mailing list/forum (see openscenegraph.org for relevant links.)  

The issue tracking system on github really isn't a good place for these type of discussions as it doesn't get seen by most of the community so far fewer people will be able to help you, and far fewer people will be able to benefit from the discussion the solutions suggested.

I am going to close this Issue here on github as it's the wrong place for this type of discussion, at this point in time it looks more like an OSG usage problem rather a bug on the OSG side.

**Closed by openscenegraph** 2018-04-01 13:51 UTC
