### ISSUE TITLE
DisplaySettings: defaults to shader hint SHADER_NONE

### ISSUE THREAD

**Issue by filnet** [openscenegraph/OpenSceneGraph#404] opened 2017-12-11 13:07 UTC
Culprit is this code in DisplaySettings::setDefaults():

#if defined(OSG_GLES3_AVAILABLE)
    setShaderHint(SHADER_GLES3);
#elif defined(OSG_GLES2_AVAILABLE)
    setShaderHint(SHADER_GLES2);
#elif defined(OSG_GL3_AVAILABLE)
    setShaderHint(SHADER_GL3);
#elif defined(OSG_GL_VERTEX_ARRAY_FUNCS_AVAILABLE)
    setShaderHint(SHADER_NONE);
#else
    setShaderHint(SHADER_GL2);
#endif

Default build of osg defines OSG_GL2_AVAILABLE and OSG_GL_VERTEX_ARRAY_FUNCS_AVAILABLE, thus the above code will set shader hint to SHADER_NONE.

**Comment by robertosfield** [comment] 2017-12-11 23:20
It's working correctly, if you don't have a build target that requires shaders then the hint doesn't need to set any particular shader preference.

Is there a problem you are seeing?

**Comment by filnet** [comment] 2017-12-12 08:30
Yes, I am seeing some shader / light / opengl related issues.

The context is an osg integration into a Qt/Qml application (i.e. osg renders to a FBO).
I did that integration 2 years ago and need to go back to it because of Qt and osg upgrades.

I'll provide more information about the issues I am running into.

**Comment by robertosfield** [comment] 2017-12-13 00:15
Are you seeing a regression due to the setShaderHint() code setting, if so which OSG version did it work previously?

Also do the OSG applications/examples work OK? i.e. does the stats handler in osgviewer work OK, display text and graph etc?

FYI, thecode you are referencing is for defaults relating to your specific build selected.  You can set the shader hint directly in your application by calling  DisplaySettings::instance()->setShaderHint(..) or by settting the env var OSG_SHADER_HINT.

**Comment by filnet** [comment] 2017-12-13 21:54
I jumped to conclusion a bit fast when accusing ShaderHint.
And, yes, osgviewer works as expected.

The cause of the "regression" is the erroneous removal of a Qt specific hack.

There is a need to call glUseProgram(0) before rendering a frame.

```
            // needed to properly render models without terrain (Qt bug?)
            QOpenGLContext::currentContext()->functions()->glUseProgram(0);
            viewer->renderingTraversals();
```

With that call things work seemingly well when loading a 3ds model.

![image](https://user-images.githubusercontent.com/8101062/33962242-2a695c22-e051-11e7-8552-5252c1e2e3f8.png)

But without it, I get this:

![1](https://user-images.githubusercontent.com/8101062/33962263-4431c0cc-e051-11e7-8e94-5efa95535066.png)

Setting OSG_SHADER_HINT to GL2 or using the osgearth_shadergen pseudo loader, yields this:

![2](https://user-images.githubusercontent.com/8101062/33962253-3810b2da-e051-11e7-9588-5932e9a606c8.png)

The rendering happens in an FBO (we use QOpenGLFramebufferObject), so the opengl context is provided by Qt. See [1] for details.
As mentioned, osgviewer.exe works fine but LibrePilot uses a home grown Qt/Qml/Osg/OsgEarth integration and things are bit more complex than in the osgviewer.
I also have to mention that I rolled my own osg::GraphicsContext to wrap the Qt provided gl context.
So a lot can go wrong on my side...

I any case, I don't understand what's going on and would like to get to the bottom of the glUseProgram(0) hack. I have basic understanding of OpenGL, FFP, shaders, etc, but don't master the nitty gritty parts of the implementations.

Moreover, LibrePilot can display more complex scenes using OsgEarth.
When using OsgEarth and the same 3ds model, a different behavior w/r to the hack is observed and other issues appear.

[1] Qt OpenGL context details

```
opengl context -----------------------------------------------------
at            : ViewportRenderer::ViewportRenderer
context       : QOpenGLContext(0xd150660)
type          : "GL"
is GLES       : false
threaded      : true
share context : QOpenGLContext(0xd1503a0)
surface ----------------------------------------
class       : "Offscreen"
type        : "OpenGLSurface"
supports GL : true
format ----------------------------------------
version : 4.6
profile : "Compatibility profile"
redBufferSize     : 8
greenBufferSize   : 8
blueBufferSize    : 8
alphaBufferSize   : 8
depthBufferSize   : 24
stencilBufferSize : 8
samples : 0
stereo : false
swapBehavior : "Double buffer"
swapInterval : 1
```

**Comment by robertosfield** [comment] 2017-12-15 12:58
There isn't any way I can pinpoint what the problem might be as it sounds very specific to setup you have. The glUseProgram(0) being needed before frame() sounds like you are running single threaded and some other code is applying a GL program that need to be switched off. This is an example of state leaking from somewhere.  You can all the code available so you will have to work out what bits of your application and dependenices are doing w.r.t state.  For instance look at Qt - its is doing GL work?

**Comment by filnet** [comment] 2017-12-15 20:23
Yes, the GL context is provided and used by Qt prior to OSG. The Qt documentation is clear about that. [1].
And I am running single threaded because Qt does not support multi-threaded access to the context.

Some questions;
- How would multi threading help in my case ?
- How can I tell my OSG scene to use FFP and not assume it is currently used ?

[1] http://doc.qt.io/qt-5/qquickframebufferobject-renderer.html#render

**Comment by robertosfield** [comment] 2017-12-15 22:52
The Qt integration issues are specific to osgQt, rather than the core OSG, osgQt now has it's own separate repository so the I think the glUseProgram(0) requirement is Qt specific integration issue that would be appropriate to post your issue on the osgQt Issue tracker rather than here.

As a general comment about the ShadeHint side of things, the OSG doesn't yet provide automatic conversion of fixed function pipeline to shaders so you can't just set the ShaderHint to GL2 and expect everything that was fixed function scene graph will map across.  If you want to use shaders then you should provide the shaders required.  The exceptions are the osgText and osgViewer::StatsHandler now (as in OSG master/3.5.9) provide shaders,  There isn't a general purpose shader implementation though.

For automatic mapping of fixed function to shaders I am working on a shader_pipeline branch that has an evolution of #pragma(tic) shader composition.  It's not complete yet, still very much bleeding edge.  My hope is to get this completed in the next couple of months and have it part of the next stable release of the OSG.

**Comment by openscenegraph** [comment] 2017-12-19 10:57
I am closing this issue as I believe it's an osgQt integration issue that best be addressed with the osgQt project, and on the shader side the LibrePilot project would need to make a decision about whether it uses the fixed function pipeline or uses shaders.

**Closed by openscenegraph** 2017-12-19 10:57 UTC

**Comment by filnet** [comment] 2017-12-19 12:08
Just to close on my side. LibrePilot does not use osgQt as we rolled our own osg/Qt/QtQuick integration.
