### ISSUE TITLE
osganimationhardware example does not work

### ISSUE THREAD

**Issue by valid-ptr** [openscenegraph/OpenSceneGraph#385] opened 2017-11-23 17:56 UTC
While running:
**osganimationhardware nathan.osg ** (skinning.vert found)
only nathan's head is visible!
+
_Warning: detected OpenGL error 'invalid operation' at after RenderBin::draw(..) in console_

PS
OSG 3.5.9 (current master)

**Comment by openscenegraph** [comment] 2017-11-24 09:26
I have just checked OSG master "osganimationhardware nathan.osg" and on my Kubunutu 16.04 + NVidia 760 it's working fine.  

What OS/hardware/driver combination are you using?

Is this a regression? If so do you know what version last worked?

**Comment by valid-ptr** [comment] 2017-11-24 12:59
I don't know if it's regression or not,
I did not run osganimation**hardware** example since OSG 3.4.0 release.

I've compiled OSG with GL2 and GL3 profiles on Linux Slackware64 14.2
**glxinfo:**
OpenGL renderer string: GeForce GTX 1050 Ti/PCIe/SSE2
OpenGL version string: 4.5.0 NVIDIA 384.98
OpenGL shading language version string: 4.50 NVIDIA

Result is always the same: only nathan's head :(

**Comment by openscenegraph** [comment] 2017-11-24 14:46
Did you test with a default build of the OSG?

**Comment by valid-ptr** [comment] 2017-11-24 15:33
Yes, same result.

_Warning: detected OpenGL error 'invalid operation' at after RenderBin::draw(..)_

**Comment by openscenegraph** [comment] 2017-11-27 09:55
I can't reproduce the issue so far.  I have similar hardware and drivers:

OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 760/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 384.90
OpenGL core profile shading language version string: 4.50 NVIDIA

Are you using OpenScenGraph-Data master?

Can you set the notify level up and then re-run your test:

  export OSG_GL_ERROR_CHECKING=ONCE_PER_ATTRIBUTE
  osganimationhardware nathan.osg &> output.txt

Then have a look through the output.txt file looking for the details of the OpenGL warning.

**Comment by mp3butcher** [comment] 2017-11-28 00:20
thanks Robert

**Comment by openscenegraph** [comment] 2017-11-28 11:00
@valid-ptr I have now merged Julien's fix to OpenSceneGraph-Data.  I hasn't change the behaviour on my system - it seem to cope just fine before, but hopefully it'll help with your drivers.  Could you do an update of OpenSceneGraph-Data and let us know if it's resolved.

**Comment by valid-ptr** [comment] 2017-11-28 11:16
Updated skinning.vert with **uint** works!

Thank you!!!

**Comment by openscenegraph** [comment] 2017-11-28 11:26
Great to hear @valid-ptr, thanks for the testing.  Thanks also to @mp3butcher for providing the fix.

**Closed by openscenegraph** 2017-11-28 11:26 UTC
