### ISSUE TITLE
Openscenegraph-3.4 branch install error with debug dll's on VS2013

### ISSUE THREAD

**Issue by remoe** [openscenegraph/OpenSceneGraph#144] opened 2016-09-29 08:11 UTC
The Openscenegraph-3.4 branch doesn't install debug dll's with cmake.  Tested it with:

https://github.com/openscenegraph/OpenSceneGraph/commit/1f9725ea4981499b43e1f250f6779a0cdc0c748d

The Openscenegraph-3.4 Tag works:

https://github.com/openscenegraph/OpenSceneGraph/tree/OpenSceneGraph-3.4.0

Maybe because of:

https://github.com/openscenegraph/OpenSceneGraph/commit/6eaf2f5781ab03c7f0c263e66eaac3f995565ae1

?

I use VS2013 on win64 with CMake 3.6.2 (older also doesn't work). Here is the error:

```
 -- Installing: x64_debug_install/bin/osg130-osgd.dll
 CMake Error at src/osg/cmake_install.cmake:55 (file):
   file INSTALL cannot find
   "x64_debug/src/osg/osg130-osgd.pdb".
 Call Stack (most recent call first):
   src/cmake_install.cmake:33 (include)
   cmake_install.cmake:96 (include)

1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: The command "setlocal\r [x64_debug\INSTALL.vcxproj]
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: cmake\bin\cmake.exe -DBUILD_TYPE=Debug -P cmake_install.cmake\r [x64_debug\INSTALL.vcxproj]
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd\r [x64_debug\INSTALL.vcxproj]
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :cmEnd\r [x64_debug\INSTALL.vcxproj]
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone\r [x64_debug\INSTALL.vcxproj]
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :cmErrorLevel\r [x64_debug\INSTALL.vcxproj]
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: exit /b %1\r [x64_debug\INSTALL.vcxproj]
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :cmDone\r [x64_debug\INSTALL.vcxproj]
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd\r [x64_debug\INSTALL.vcxproj]
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: :VCEnd" exited with code 1. [x64_debug\INSTALL.vcxproj]
```

**Comment by robertosfield** [comment] 2016-09-29 14:05
Hi,

I'm not a Windows developer so not best placed to help work out what the issue is and how to resolve it.

Could you raise this issue on the osg-users mailing/forum as this is the best way to broadcast the issue to the community and get a response from the Windows users in the community.  

The github issue tracker doesn't tend to get visited by many OSG users/contributors so just posting issues here won't get the exposure it needs to resolve it in a timely manner.

Thanks.

**Comment by openscenegraph** [comment] 2016-10-07 15:57
Thanks to Laurens we now have a fix for this issue.  I'll close this issue now, if there is any remaining problems please raise the issue on osg-users mailing list/forum as this will get the widest exposure.

**Closed by openscenegraph** 2016-10-07 15:57 UTC
