### ISSUE TITLE
OpenSceneGraph 3.6 huge memory leak with osgText (default font)

### ISSUE THREAD

**Issue by valid-ptr** [openscenegraph/OpenSceneGraph#806] opened 2019-07-30 14:14 UTC
There is a huge memory leak (every frame) while using "default" font (font not found).
Just enable StatsHandler to see memleak.

**Comment by openscenegraph** [comment] 2019-07-30 15:31
Could you give me some info about how you are determining that there is a memory leak?

What platform and applications are you testing with?

**Comment by openscenegraph** [comment] 2019-07-30 17:41
I've been looking into this and I believe the problem is that the Text::getActiveFontI()'s mechanism of falling back to DefaultFont isn't taking a reference as it should be, then the ObjectCache is removing the Font after it's hung around without any references, this then forces a new DefaultFont to be created. Which does occasionally cause a seg fault for me in TExt::drawImplementation() as well.   

This all stems from the change to DefaultFont being pushed into ObjectCache rather than having a local static ref_ptr<> so it kinds looks like that change was a mistake.  Will have a think about how to resolve this.

**Comment by openscenegraph** [comment] 2019-07-31 13:30
The newly introduced bug discussed above turns out to be due to the DefaultFont being used by Text without taking a reference to it so that when the ObjectCache is flushed on unused objects it clears the DefaultFont assigned to it as it doesn't have any external references, when it's deleted the next time the DefaultFont is needed and new one is created.

To fix this I've had to add a ref_ptr<Font> _fontFallback to TextBase, this change ensures that only one DefaultFont is created and avoids the memory growth:

https://github.com/openscenegraph/OpenSceneGraph/commit/149c04b0df37e605a94495363801eb518b58a059

**Closed by openscenegraph** 2019-07-31 13:30 UTC
